name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 22f1001519@ds.study.iitm.ac.in
        run: echo "This step is named with an email address."
